#!/bin/bash

echo "=========================================="
echo "SSH PRIVATE KEY for GitHub Secret"
echo "=========================================="
echo ""
echo "1. Copy EVERYTHING between the lines below (including BEGIN and END lines)"
echo "2. Go to: https://github.com/DavidWeinzierl/speakersite2/settings/secrets/actions"
echo "3. Delete the existing SSH_PRIVATE_KEY secret"
echo "4. Create a new SSH_PRIVATE_KEY secret"
echo "5. Paste the ENTIRE key exactly as shown below"
echo ""
echo "=========================================="
echo "START COPYING FROM NEXT LINE:"
echo "=========================================="
cat .github/deploy_key_rsa
echo "=========================================="
echo "STOP COPYING AT PREVIOUS LINE"
echo "=========================================="
echo ""
echo "Key info:"
ssh-keygen -l -f .github/deploy_key_rsa
echo ""
echo "IMPORTANT: Make sure you paste the ENTIRE key including:"
echo "  - The -----BEGIN OPENSSH PRIVATE KEY----- line"
echo "  - All the lines in between"
echo "  - The -----END OPENSSH PRIVATE KEY----- line"
echo ""
echo "Do NOT add any extra blank lines before or after!"
