#!/bin/bash
# Verify GitHub Secrets Configuration
# This script helps you check if your secrets are set correctly

echo "🔍 GitHub Secrets Verification Helper"
echo "======================================"
echo ""
echo "Go to: https://github.com/DavidWeinzierl/speakersite2/settings/secrets/actions"
echo ""
echo "You should have these 5 secrets configured:"
echo ""

echo "1️⃣  SSH_PRIVATE_KEY"
echo "   Status: Should show as 'Updated X days ago'"
echo "   Value starts with: -----BEGIN OPENSSH PRIVATE KEY-----"
echo "   Value ends with: -----END OPENSSH PRIVATE KEY-----"
echo "   IMPORTANT: Copy the ENTIRE key including BEGIN/END lines"
echo "   From: cat .github/deploy_key_rsa"
echo ""

echo "2️⃣  SSH_HOST"
echo "   Current value should be: www93.world4you.com"
echo "   ⚠️  CHECK: No extra spaces, quotes, or special characters!"
echo "   Test locally:"
echo "   ping www93.world4you.com"
ping -c 1 www93.world4you.com 2>/dev/null && echo "   ✅ Host resolves correctly" || echo "   ❌ Host does not resolve"
echo ""

echo "3️⃣  SSH_PORT"
echo "   Value: 22"
echo ""

echo "4️⃣  SSH_USER"
echo "   Value: ftp6887902"
echo ""

echo "5️⃣  SSH_DESTINATION"
echo "   Value: /home/.sites/872/site6887902/speakersite2/build"
echo "   (This is where the build files will be synced)"
echo ""

echo "🔧 Common Issues:"
echo ""
echo "Issue: 'Could not resolve hostname ***'"
echo "Fix: SSH_HOST secret likely has:"
echo "  - Extra spaces before/after the hostname"
echo "  - Quotes around the hostname (don't use quotes)"
echo "  - Hidden characters (copy-paste issue)"
echo "  - Wrong hostname"
echo ""
echo "Solution: Delete the SSH_HOST secret and recreate it"
echo "1. Type EXACTLY: www93.world4you.com"
echo "2. No quotes, no spaces, just the hostname"
echo ""

echo "Issue: 'Permission denied (publickey)'"
echo "Fix: SSH_PRIVATE_KEY is incomplete or wrong format"
echo "Solution: Copy the ENTIRE key file:"
cat .github/deploy_key_rsa
echo ""

echo "🧪 Test Secrets Locally"
echo "======================="
echo ""
echo "To test if your secrets would work, run:"
echo ""
echo "ssh -i .github/deploy_key_rsa -p 22 ftp6887902@www93.world4you.com 'echo Success'"
echo ""
echo "If that works locally, your GitHub secrets should use the same values."
echo ""

echo "📝 After Updating Secrets"
echo "========================="
echo "1. Commit and push any changes:"
echo "   git add .github/workflows/"
echo "   git commit -m 'Fix GitHub Actions deployment'"
echo "   git push origin main"
echo ""
echo "2. Watch the action run at:"
echo "   https://github.com/DavidWeinzierl/speakersite2/actions"
echo ""
echo "3. Check the logs for the debug output we added"
echo ""
